server.servlet.context-path=/shopping-cart-app
spring.application.name=shopping-cart-pricing-service
server.port=8080

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration,\
org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# Swagger UI config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/swagger/shoppingCart.yaml
springdoc.swagger-ui.disable-swagger-default-url=true


shopping.cart.redis.enabled=false
redis.host=http://localhost:8099/

